# Disable the newline at the start of the prompt
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[î€](bold green)"

[conda]
symbol = "îœ¼ "
format = "[$symbol$environment](green) "

[cmd_duration]
min_time = 2000
format = "took [$duration]($style)"
style = "yellow"

[directory]
truncation_length = 4
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "
style = "bold cyan"

[jobs]
symbol = "ï€“ "
threshold = 1

[git_branch]
symbol = "ï˜ "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 5

[git_state]
cherry_pick = "ğŸ’ PICKING"

[git_status]
ahead = "â‡¡"
behind = "â‡£"
staged.style = "green"

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[memory_usage]
symbol = "ï¡š "

[docker_context]
symbol = "ïŒˆ "

[nodejs]
symbol = "î‰ "

[hostname]
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "î¨ "

[time]
time_format = "%T"
format = "at [$time]($style) "

[username]
disabled = true
show_always = false
style_user = "green"
style_root = "bold red"
