# Disable the newline at the start of the prompt
add_newline = true

prompt_order = [
    "time",
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "python",
    "conda",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "character"
]

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[character]
symbol = "âœ"
vicmd_symbol = "î€"
error_symbol = "âœ—"
use_symbol_for_status = true
style_success = "bold green"
style_failure = "bold red"

[cmd_duration]
disabled = false
min_time = 2000
prefix = "took "
style = "yellow"

[conda]
symbol = "ï„Œ "
style = "dimmed green"

[directory]
truncation_length = 4
truncate_to_repo = true
prefix = "in "
style = "bold cyan"

[jobs]
symbol = "ï€“ "
threshold = 1

[git_branch]
symbol = "ï˜ "
truncation_length = 4
truncation_symbol = ""

[git_commit]
commit_hash_length = 5

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "î€Š"
deleted = "ïš¿"
ahead = "â‡¡"
behind = "â‡£"
staged.value = "ï•"
staged.style = "green"
staged_count.enabled = true
staged_count.style = "green"
stashed = "ï€œ"
modified = "ïª"
# conflicted = "ğŸ³"
# ahead = "ğŸğŸ’¨"
# behind = "ğŸ˜°"
# diverged = "ğŸ˜µ"
# untracked = "ğŸ¤·"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# renamed = "ğŸŒ—"
# deleted = "ğŸ—‘"

[battery]
full_symbol = "ï•¸"
charging_symbol = "ï–ƒ"
discharging_symbol = "ï–‚"

[memory_usage]
symbol = "ï¡š "

[nodejs]
symbol = "î‰ "

[hostname]
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[python]
symbol = "î˜† "
pyenv_version_name = true
pyenv_prefix = "pyenv "

[ruby]
symbol = "îˆ¾ "

[rust]
symbol = "ï€“ "

[time]
disabled = false
format = "%T"

[username]
disabled = true
show_always = false
style_user = "green"
style_root = "bold red"
